### ISSUE TITLE
Quaternion class

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboTeamTwente/roboteam_utils#28]

**Comment by HaicoDorenbos** [comment]
If you would provide more reasons why you think this class is needed, then it might be considered. :thinking:

**Comment by rolfvdhulst** [comment]
It was a good idea back then but I don't anymore think we should make our own to be honest.
Eigen::QuaternionD is more than sufficient in most cases, and we use Eigen::Vector3d for 3d calculations anyways. Unfortunately it is very hard to superclass Eigen, but what we can do is e.g. make a namespace with some utility functions.
